### PR TITLE
Add `when_race()`

### LINKED ISSUE #76: Do we need `when_race()`?
I missed an issue in the `cleanup_tree` tests because errors thrown in `action` are silently ignored in `when_any()`. Is this expected behaviour? I would have expected an error here.

```r
defer_fail <- function() {
  deferred$new(action = function(resolve) stop("foo"))
}

synchronise(when_all(
  delay(0.1),
  defer_fail()
))
#> Error:
#> ! foo

synchronise(when_any(
  delay(0.1),
  defer_fail()
))
#> [1] TRUE
```

### PR DESCRIPTION
**Pull request by lionel-**
Closes #76

### CODE REVIEW

**Review by gaborcsardi — COMMENTED** [review]
Thanks! I would not change `when_some()` but rather have an internal function that implements both `race = TRUE` and `race = FALSE`. I think that's a cleaner API.

**Comment by lionel-** [comment]
I was thinking that it made sense to use `when_some()` with rejections enabled?

**Comment by gaborcsardi** [comment]
I think then it is better to implement the `count` parameter of `when_race()`.

**Comment by gaborcsardi** [comment]
@lionel I updated the API to better match the existing functions.

**Comment by lionel-** [comment]
Thanks, this looks good

**Comment by gaborcsardi** [comment]
Thank you!

**Pull request merged**
